Description: >
  This CloudFormation template deploys a full CI/CD pipeline whih will deploy all helper resources for the project and set up global parameters.

Parameters:
  ProjectID:
    Description: A unique value to identify the project that will be used to partially name resources in this template.
    AllowedPattern: ^[0-9a-z]+([0-9a-z-]*[0-9a-z])*$
    ConstraintDescription: ProjectID can include numbers, lowercase letters, and hyphens (-), first character must be a letter. It cannot start or end with a hyphen(-).
    Default: proj01
    Type: String

  Email:
    Description: The email address where to send notifications
    Default: yauhen.volkau@gmail.com
    Type: String

  EnvironmentType:
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - tst
      - acc
      - prd

  GitHubOAuthToken:
    Description: Create a token with 'repo' and 'admin:repo_hook' permissions here https://github.com/settings/tokens
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'

  GitHubUser:
    Description: Enter GitHub username of the repository owner
    Type: String
    Default: User
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepository:
    Description: Enter the repository name that should be monitored for changes
    Type: String
    Default: Prj01-helperresources

  GitHubBranch:
    Description: Enter the GitHub branch to monitored
    Type: String
    Default: master

  Region:
    Description: Type a correct region to find S3 bucket with CF child templates.
    AllowedPattern: ^[0-9a-z]+([0-9a-z-]*[0-9a-z])*$
    ConstraintDescription: Region name can include numbers, lowercase letters and hyphens (-). It cannot start or end with a hyphen (-).
    Default: eu-central-1
    Type: String

Conditions:
  CreateDevResources: !Equals [ !Ref EnvironmentType, dev ]
  CreateTstResources: !Equals [ !Ref EnvironmentType, tst ]
  CreateAccResources: !Equals [ !Ref EnvironmentType, acc ]
  CreatePrdResources: !Equals [ !Ref EnvironmentType, prd ]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Application Configuration
          Parameters:
            - ProjectID
      - Label:
          default: GitHub Configuration
          Parameters:
            - GitHubOAuthToken
            - GitHubUser
            - GitHubRepository
            - GitHubBranch

    ParameterLabels:
      ProjectID:
        default: Customer ID
      GitHubRepository:
        default: Repository Name
      GitHubUser:
        default: Repository Owner
      GitHubBranch:
        default: Repository Branch
      GitHubOAuthToken:
        default: OAuth2 Token

Resources:
# SNS Topic
  CodePipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email
# S3 Buckets (this bucket will have to be manaully emptied before deleting cloudformation stack).
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join [ '-', [ !Ref ProjectID, !Ref EnvironmentType, 'helper-artifacts'] ]
      
# CodeBuild IAM Role
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ProjectID}-${EnvironmentType}-${AWS::Region}-CodeBuild-Role
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: !Sub ${ProjectID}-${EnvironmentType}-${AWS::Region}-CodeBuild-Policy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Resource: "*"
              Action:
              - iam:PassRole
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - greengrass:*
              - cloudformation:ListExports
            - Effect: Allow
              Resource: !Sub "arn:aws:s3:::*/*"
              Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
      
# CodeBuild Project
  PackageCFTemplates:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join [ "-", [ !Ref ProjectID, !Ref EnvironmentType, "PackageCFTemplates"] ]
      Description: !Sub Build project for ${ProjectID}
      ServiceRole: !Ref CodeBuildRole
      Source:
        BuildSpec: buildspec.yaml
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:10.14.1
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_S3_BUCKET
            Value: !Sub ${ArtifactBucket}
      Artifacts:
        Name: !Ref ProjectID
        Type: CODEPIPELINE
        
# CodePipeline IAM Role
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ProjectID}-${EnvironmentType}-${AWS::Region}-CodePipeline
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
      Policies:
        - PolicyName: !Sub ${ProjectID}-${EnvironmentType}-${AWS::Region}-CodePipeline
          PolicyDocument:
            Statement:
              - Action:
                - s3:GetBucketVersioning
                Resource:
                  - !Join [ "", [ "arn:aws:s3:::", !Ref ArtifactBucket ] ]
                Effect: Allow
              - Action:
                - s3:PutObject
                - s3:GetObject
                - S3:GetObjectVersion
                Resource:
                  - !Join [ "", [ "arn:aws:s3:::", !Ref ArtifactBucket, "/*" ] ]
                Effect: Allow
              - Action:
                - codedeploy:CreateDeployment
                - codedeploy:GetApplicationRevision
                - codedeploy:GetDeployment
                - codedeploy:GetDeploymentConfig
                - codedeploy:RegisterApplicationRevision
                - cloudformation:CreateStack
                - cloudformation:DeleteStack
                - cloudformation:DescribeStacks
                - cloudformation:UpdateStack
                - cloudformation:CreateChangeSet
                - cloudformation:DeleteChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:ExecuteChangeSet
                - cloudformation:SetStackPolicy
                - cloudformation:ValidateTemplate
                - iam:PassRole
                - codebuild:BatchGetBuilds
                - codebuild:StartBuild
                - 'sns:Publish'
                - 'lambda:*'
                - 'codebuild:*'
                Resource: "*"
                Effect: Allow

# CodePipeline-CloudFormation IAM Role
  CodePipelineCloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${ProjectID}-${EnvironmentType}-${AWS::Region}-CloudFormation
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyName: !Sub ${ProjectID}-${EnvironmentType}-${AWS::Region}-CloudFormation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: "*"
              Resource: "*"

# CodePipeline          
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join [ "-", [ !Ref ProjectID, !Ref EnvironmentType, 'helperresources' ] ]
      RoleArn: !Sub ${CodePipelineRole.Arn}
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                -  Name: Source
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
        - Name: CodeBuild
          Actions:
            - Name: PackageCFTemplates
              RunOrder: 1
              InputArtifacts:
                - Name: Source
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Build
              Configuration:
                ProjectName: !Ref PackageCFTemplates
    # Pipeline - Lambda Function Helpers
        - Name: BuildResources
          Actions:    
            - !If
              - CreateDevResources
              - Name: CreateLFHelpersChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                InputArtifacts:
                  - Name: Source
                  - Name: Build
                OutputArtifacts:
                  - Name: CreateLambdaHelpersChangeSet
                Configuration:
                  ActionMode: CHANGE_SET_REPLACE
                  Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                  RoleArn: !GetAtt [CodePipelineCloudFormationRole, Arn]
                  ChangeSetName: !Join [ "-", [ !Ref ProjectID, !Ref EnvironmentType, "lambdaHelpers"] ]
                  StackName: !Join [ "-", [ !Ref ProjectID, !Ref EnvironmentType, "lambdaHelpers"] ]
                  TemplatePath: !Sub "Build::lambdaHelpers.yaml"
                RunOrder: 10
              - !Ref AWS::NoValue
            - !If
              - CreateDevResources
              - Name: ExecuteLambdaHelpersChangeSet
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CloudFormation
                  Version: 1
                Configuration:
                  ActionMode: CHANGE_SET_EXECUTE
                  ChangeSetName: !Join [ "-", [ !Ref ProjectID, !Ref EnvironmentType, "lambdaHelpers"] ]
                  RoleArn: !GetAtt [CodePipelineCloudFormationRole, Arn]
                  StackName: !Join [ "-", [ !Ref ProjectID, !Ref EnvironmentType, "lambdaHelpers"] ]
                RunOrder: 11
              - !Ref AWS::NoValue
Outputs:
  ProjectID:
    Value: !Ref ProjectID
    Export:
      Name: ProjectID
  EnvironmentType:
    Value: !Ref EnvironmentType
    Export:
      Name: EnvironmentType
  Region:
    Value: !Ref Region
    Export:
      Name: Region
