version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entering the build phase...
      - echo Building started on `date`
      - aws cloudformation package --template-file cloudformation/lambdahelpers/lambdaHelpers.yaml.yaml --s3-bucket $ARTIFACT_S3_BUCKET --output-template-file lambdaHelpers.yaml.yaml
      - aws cloudformation package --template-file cloudformation/pipelines/pipeline-helpers.yaml --s3-bucket $ARTIFACT_S3_BUCKET --output-template-file pipeline-helpers.yaml
      - aws cloudformation package --template-file cloudformation/pipelines/pipeline-resources.yaml --s3-bucket $ARTIFACT_S3_BUCKET --output-template-file pipeline-resources.yaml
      - aws cloudformation package --template-file cloudformation/pipelines/pipeline-website.yaml --s3-bucket $ARTIFACT_S3_BUCKET --output-template-file pipeline-website.yaml
    finally:
      - echo This always runs even if the install command fails
artifacts:
  type: zip
  files:
    - 'lambdaHelpers.yaml'
    - 'pipeline-helpers.yaml'
    - 'pipeline-resources.yaml'
    - 'pipeline-website.yaml'
  discard-paths: yes