version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entering the build phase...
      - echo Building started on `date`
      - aws cloudformation package --template-file LambdaFunctions.yaml --s3-bucket $ARTIFACT_S3_BUCKET --output-template-file LambdaFunctions.yaml
    finally:
      - echo This always runs even if the install command fails
artifacts:
  type: zip
  files:
    - 'LambdaFunctions.yaml'
  discard-paths: yes